name: test with simulator targets on RSA/ECC to detect xmalloc failures

on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

jobs:
  simulator_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: make clean
        run: |
          make distclean

      - name: Select config (64 bit simulator)
        run: |
          cp config/examples/sim.config .config

      - name: Build tools
        run: |
          make -C tools/keytools && make -C tools/bin-assemble

      - name: Build wolfboot.elf (ECC256)
        run: |
          make clean && make test-sim-internal-flash-with-update SIGN=ECC256

      - name: Run sunny day update test
        run: |
          tools/scripts/sim-sunnyday-update.sh

      - name: Build wolfboot.elf (ECC256, WOLFBOOT_SMALL_STACK)
        run: |
          make clean && make test-sim-internal-flash-with-update SIGN=ECC256 WOLFBOOT_SMALL_STACK=1

      - name: Run sunny day update test
        run: |
          tools/scripts/sim-sunnyday-update.sh

